## Install libraries

Theano is an open source numerical computation library very efficient for fast computation and is based on Numpy syntax. Can be runned on CPU and GPU

Why GPU is preferred?
    It is used for graphic purposes. In terms of power and efficiency it is higher. forward propagating and back propagation involves parallel computation.
    
Keras: It is a wrapper class. It is based on Theano and Tensorflow

For Mac users: 
 
Open your main terminal or the Anaconda Prompt and enter the following commands: 
 
pip install theano pip install tensorflow pip install keras conda update --all 
 
 
For Windows and Linux users: 
 
In Spyder, go to Tools and Open Anaconda Prompt. Then enter the following commands: 
1. Create a new environment with Anaconda and Python 3.5:
    conda create -n tensorflow python=3.5 anaconda 
2. Activate the environment: 
    activate tensorflow
3. After this you can install Theano, TensorFlow and Keras: 
    conda install theano conda install mingw libpython pip install tensorflow pip install keras 
4. Update the packages: 
    conda update --all 5. Run Spyder: spyder 
 
To install TensorFlow on your GPU (optional): pip install tensorflow-gpu 

## Data Preprocessing

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Import encoders
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#Import data split
from sklearn.cross_validation import train_test_split

#Import standardisation
from sklearn.preprocessing import StandardScaler

# Import Neural Network Wrapper
import keras

#Sequential module is required to initialize our neural network.
from keras.models import Sequential

#Dense module is required to build layers of ANN.
from keras.layers import Dense

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Using TensorFlow backend.


In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()

X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

X

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.02000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   7.09000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  1.00000000e+00,   0.00000000e+00,   7.72000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   7.92000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [5]:
# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [7]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [8]:
#Initialization of ANN
classifier = Sequential()

In [9]:
# adding input layers and first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim= 11))
#init is for weights

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, input_dim=11, activation="relu")`
  


In [10]:
#adding second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=6)`
  


In [11]:
#output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
  


In [12]:
#compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
#fit 
classifier.fit(X_train, y_train, batch_size = 10 , nb_epoch=100)

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py:939: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.4861 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4272 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4208 - acc: 0.8055
Epoch 4/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.4174 - acc: 0.8242
Epoch 5/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4151 - acc: 0.8271
Epoch 6/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4136 - acc: 0.8296
Epoch 7/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4119 - acc: 0.8311
Epoch 8/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4097 - acc: 0.8334
Epoch 9/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4064 - acc: 0.8339
Epoch 10/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.4049 - acc: 0.8342

In [14]:
#Predict
y_pred = classifier.predict(X_test)

y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [15]:
#Confusion MAtrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1477,  118],
       [ 174,  231]], dtype=int64)

In [16]:
(1477+231)/2000

0.854

In [17]:
new_prediction = classifier.predict(sc.fit_transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [18]:
new_prediction

array([[ 0.06582124]], dtype=float32)

In [19]:
new_prediction = new_prediction>0.5

In [20]:
new_prediction

array([[False]], dtype=bool)

## K Fold Cross Validation

In [21]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [22]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim= 11))
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))
    classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return classifier


In [23]:
classifier = KerasClassifier(build_fn=build_classifier,batch_size = 10 , nb_epoch=100)

In [ ]:
accuracies = cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10,n_jobs=-1)

In [ ]:
mean = accuracies.mean()
variance = accuracies.std()

## Regularization

In [24]:
from keras.layers import Dropout

In [26]:
#Initialization of ANN
classifier = Sequential()

In [27]:
# adding input layers and first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim= 11))
classifier.add(Dropout(p=0.1))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, input_dim=11, kernel_initializer="uniform")`
  
C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  This is separate from the ipykernel package so we can avoid doing imports until


In [28]:
#adding second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [29]:
#output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [30]:
#compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [31]:
#fit 
classifier.fit(X_train, y_train, batch_size = 10 , nb_epoch=100)

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py:939: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 2s 294us/step - loss: 0.6087 - acc: 0.7995
Epoch 2/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.4889 - acc: 0.8346
Epoch 3/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4287 - acc: 0.8440
Epoch 4/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4024 - acc: 0.8440
Epoch 5/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3926 - acc: 0.8464
Epoch 6/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.3852 - acc: 0.8425
Epoch 7/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3786 - acc: 0.8475
Epoch 8/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3758 - acc: 0.8456
Epoch 9/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.3782 - acc: 0.8464
Epoch 10/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3760 - acc: 0.8450

Epoch 82/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3575 - acc: 0.8505
Epoch 83/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3610 - acc: 0.8517
Epoch 84/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.3573 - acc: 0.8534
Epoch 85/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.3565 - acc: 0.8520
Epoch 86/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3609 - acc: 0.8534
Epoch 87/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.3622 - acc: 0.8495
Epoch 88/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3630 - acc: 0.8507
Epoch 89/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.3564 - acc: 0.8527
Epoch 90/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3567 - acc: 0.8541
Epoch 91/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3596 - ac

## Grid Search

In [32]:
#Tuning the ANN

In [8]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [9]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim= 11))
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))
    classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return classifier


In [10]:
classifier = KerasClassifier(build_fn=build_classifier)

In [11]:
parameters = {'batch_size': [25,32], 
              'nb_epoch' : [100,500],
              'optimizer':['adam','rmsprop']}

In [12]:
grid_search = GridSearchCV(estimator=classifier,
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv =10)

In [13]:
grid_search = grid_search.fit(X_train,y_train)

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", input_dim=11, units=6)`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=6)`
  after removing the cwd from sys.path.
C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
  """


Epoch 1/1
7200/7200 [==============================] - 0s 18us/step
Epoch 1/1
7200/7200 [==============================] - 0s 29us/step
Epoch 1/1
7200/7200 [==============================] - 0s 24us/step
Epoch 1/1
7200/7200 [==============================] - 0s 25us/step
Epoch 1/1
7200/7200 [==============================] - 0s 23us/step
Epoch 1/1
7200/7200 [==============================] - 0s 33us/step
Epoch 1/1
7200/7200 [==============================] - 0s 23us/step
Epoch 1/1
7200/7200 [==============================] - 0s 55us/step
Epoch 1/1
7200/7200 [==============================] - 0s 20us/step
Epoch 1/1
7200/7200 [==============================] - 0s 26us/step
Epoch 1/1
7200/7200 [==============================] - 0s 22us/step
Epoch 1/1
7200/7200 [==============================] - 0s 25us/step
Epoch 1/1
7200/7200 [==============================] - 0s 26us/step
Epoch 1/1
7200/7200 [==============================] - 0s 26us/step
Epoch 1/1
7200/7200 [===========================

7200/7200 [==============================] - 0s 26us/step
Epoch 1/1
7200/7200 [==============================] - 0s 26us/step
Epoch 1/1
7200/7200 [==============================] - 0s 24us/step
Epoch 1/1
7200/7200 [==============================] - 0s 22us/step
Epoch 1/1
7200/7200 [==============================] - 0s 21us/step
Epoch 1/1
7200/7200 [==============================] - 0s 47us/step
Epoch 1/1
7200/7200 [==============================] - 0s 28us/step
Epoch 1/1
7200/7200 [==============================] - 0s 23us/step
Epoch 1/1
7200/7200 [==============================] - 0s 32us/step
Epoch 1/1
7200/7200 [==============================] - 0s 40us/step
Epoch 1/1
7200/7200 [==============================] - 0s 34us/step
Epoch 1/1
7200/7200 [==============================] - 0s 36us/step
Epoch 1/1
7200/7200 [==============================] - 0s 35us/step
Epoch 1/1
7200/7200 [==============================] - 0s 21us/step
Epoch 1/1
7200/7200 [==============================] - 0s 

Epoch 1/1
7200/7200 [==============================] - 0s 33us/step
Epoch 1/1
7200/7200 [==============================] - 0s 28us/step
Epoch 1/1
7200/7200 [==============================] - 0s 37us/step
Epoch 1/1
8000/8000 [==============================] - 3s 364us/step - loss: 0.5636 - acc: 0.7946


In [14]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [15]:
best_accuracy

0.79600000000000004

In [16]:
best_accuracy

0.79600000000000004

In [46]:
best_parameters

{'batch_size': 25, 'nb_epoch': 100, 'optimizer': 'adam'}