## Install libraries

Theano is an open source numerical computation library very efficient for fast computation and is based on Numpy syntax. Can be runned on CPU and GPU

Why GPU is preferred?
    It is used for graphic purposes. In terms of power and efficiency it is higher. forward propagating and back propagation involves parallel computation.
    
Keras: It is a wrapper class. It is based on Theano and Tensorflow

For Mac users: 
 
Open your main terminal or the Anaconda Prompt and enter the following commands: 
 
pip install theano pip install tensorflow pip install keras conda update --all 
 
 
For Windows and Linux users: 
 
In Spyder, go to Tools and Open Anaconda Prompt. Then enter the following commands: 
1. Create a new environment with Anaconda and Python 3.5:
    conda create -n tensorflow python=3.5 anaconda 
2. Activate the environment: 
    activate tensorflow
3. After this you can install Theano, TensorFlow and Keras: 
    conda install theano conda install mingw libpython pip install tensorflow pip install keras 
4. Update the packages: 
    conda update --all 5. Run Spyder: spyder 
 
To install TensorFlow on your GPU (optional): pip install tensorflow-gpu 

## Data Preprocessing

In [39]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Import encoders
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#Import data split
from sklearn.cross_validation import train_test_split

#Import standardisation
from sklearn.preprocessing import StandardScaler

# Import Neural Network Wrapper
import keras

#Sequential module is required to initialize our neural network.
from keras.models import Sequential

#Dense module is required to build layers of ANN.
from keras.layers import Dense

In [54]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [55]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [57]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()

X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

X

array([[  0.00000000e+00,   0.00000000e+00,   2.28000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.17000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.11000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   3.18000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  0.00000000e+00,   1.00000000e+00,   3.81000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   4.01000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [58]:
# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [59]:
# Feature Scaling

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [60]:
X_train

array([[ 1.74309049, -0.5698444 ,  0.1692298 , ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-0.57369368,  1.75486502, -2.30959   , ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.57369368, -0.5698444 , -1.19412109, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.57369368, -0.5698444 ,  0.90254733, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [ 1.74309049, -0.5698444 , -0.62605822, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.57369368,  1.75486502, -0.28522049, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [61]:
#Initialization of ANN
classifier = Sequential()

In [63]:
# adding input layers and first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim= 11))
#init is for weights

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", input_dim=11, units=6, activation="relu")`
  


In [64]:
#adding second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, activation="relu")`
  


In [65]:
#output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=1, activation="sigmoid")`
  


In [66]:
#compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [67]:
#fit 
classifier.fit(X_train, y_train, batch_size = 10 , nb_epoch=100)

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py:939: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 2s 285us/step - loss: 0.4788 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4282 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.4220 - acc: 0.8097
Epoch 4/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.4187 - acc: 0.8214
Epoch 5/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.4161 - acc: 0.8261
Epoch 6/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4144 - acc: 0.8287
Epoch 7/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.4130 - acc: 0.8312
Epoch 8/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.4116 - acc: 0.8335
Epoch 9/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.4096 - acc: 0.8334
Epoch 10/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.4095 - acc: 0.8341

8000/8000 [==============================] - 1s 176us/step - loss: 0.3983 - acc: 0.8364
Epoch 82/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.3978 - acc: 0.8359
Epoch 83/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.3983 - acc: 0.8365
Epoch 84/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3980 - acc: 0.8359
Epoch 85/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3976 - acc: 0.8342
Epoch 86/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3969 - acc: 0.8367
Epoch 87/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.3974 - acc: 0.8370
Epoch 88/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3975 - acc: 0.8367
Epoch 89/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.3977 - acc: 0.8361
Epoch 90/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.3973 - acc: 0.8339
Epo

In [72]:
#Predict
y_pred = classifier.predict(X_test)

y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [74]:
#Confusion MAtrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
    

array([[1539,   56],
       [ 251,  154]], dtype=int64)

In [75]:
(1539+154)/2000

0.8465

In [76]:
new_prediction = classifier.predict(sc.fit_transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))

C:\Users\aswat\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [77]:
new_prediction

array([[ 0.3920522]], dtype=float32)

In [78]:
new_prediction = new_prediction>0.5

In [79]:
new_prediction

array([[False]], dtype=bool)